name: datathon-8mlet-grupo-18

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ptsantos/private:datathon-8mlet-grupo-18
    ports:
      - "${API_PORT:-8081}:8081"
    env_file: ".env"
    command:
      - "uvicorn"
      - "datathon_mlet.api.entrypoints.main:app"
      - "--host"
      - "${API_HOST:-0.0.0.0}"
      - "--port"
      - "${API_PORT:-8081}"
      - "--workers"
      - "${WEB_CONCURRENCY:-1}"
